name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t package

      - name: Bundle Lambda code
        run: |
          cp lambda_function.py package/
          cd package
          zip -r ../lambda_package.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # update as needed

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:524618625487:function:LineBot-Automation-Test \
            --zip-file fileb://lambda_package.zip
